import pandas as pd

# Specify the CSV file and chunk size
csv_file = 'data/books.csv'
chunk_size = 10000  # You can adjust this based on your system's memory constraints

# Create an empty DataFrame to store the selected books
selected_books_df = pd.DataFrame()

# Create a list of book titles you want to select
titles_to_select = [
    "To Kill a Mockingbird",
    "1984",
    "Pride and Prejudice",
    "The Great Gatsby",
    "The Catcher in the Rye",
    "Moby-Dick",
    "The Lord of the Rings",
    "The Hobbit",
    "The Odyssey",
    "The Iliad",
    "The Harry Potter series",
    "War and Peace",
    "Crime and Punishment",
    "The Chronicles of Narnia",
    "Brave New World",
    "The Hitchhiker's Guide to the Galaxy",
    "Frankenstein",
    "The Grapes of Wrath",
    "One Hundred Years of Solitude",
    "The Road",
    "The Adventures of Huckleberry Finn",
    "The Brothers Karamazov",
    "The Picture of Dorian Gray",
    "The Count of Monte Cristo",
    "The Little Prince",
    "The Stranger",
    "The Scarlet Letter",
    "The Kite Runner",
    "The Shining",
    "The Martian",
    "The Giver",
    "The Alchemist",
    "The Color Purple",
    "The Book Thief",
    "Slaughterhouse-Five",
    "The Silence of the Lambs",
    "The Hunger Games",
    "The Road Less Traveled",
    "The Wind in the Willows",
    "The Sun Also Rises",
    "Wuthering Heights",
    "The Secret Garden",
    "The Diary of Anne Frank",
    "The Bell Jar",
    "The Glass Castle",
    "The Girl with the Dragon Tattoo",
    "The Help",
    "The Name of the Wind",
    "The Road to Character",
    "A Tale of Two Cities",
    "Dracula",
    "The Fountainhead",
    "The Stand",
    "The Art of War",
    "The Immortal Life of Henrietta Lacks",
    "The Old Man and the Sea",
    "The Picture of Dorian Gray",
    "The Time Traveler's Wife",
    "The Witching Hour",
    "The Year of Living Biblically",
    "Fahrenheit 451",
    "The Jungle",
    "A Clockwork Orange",
    "The Metamorphosis",
    "The Da Vinci Code",
    "Ender's Game",
    "The Joy Luck Club",
    "The Nightingale",
    "The Road",
    "The Stand",
    "The Stranger Beside Me",
    "The White Tiger",
    "The Woman in White",
    "To the Lighthouse",
    "Walden",
    "Where the Crawdads Sing",
    "White Fang",
    "Wild: From Lost to Found on the Pacific Crest Trail",
    "Zen and the Art of Motorcycle Maintenance",
    "The Devil in the White City",
    "The Road to Character",
    "The Immortal Life of Henrietta Lacks",
    "Educated",
    "Born a Crime",
    "The Silent Patient",
    "The Water Dancer",
    "The Vanishing Half",
    "Normal People",
    "The Testaments",
    "Where the Forest Meets the Stars",
    "The Night Circus",
    "The Glass Hotel",
    "The Girl on the Train",
    "The Silent Patient",
    "The Tattooist of Auschwitz",
    "The Goldfinch",
    "A Man Called Ove",
    "The Underground Railroad",
    "The Immortalists",
    "The Silent Patient",
]

for chunk in pd.read_csv(csv_file, chunksize=chunk_size):
    # Filter rows based on the batch of titles
    batch_selected = chunk[chunk['Book-Title'].isin(titles_to_select)]
    
    # Concatenate the batch with the selected_books DataFrame
    selected_books_df = pd.concat([selected_books_df, batch_selected], ignore_index=True)

# Save the selected books to a new CSV file
selected_books_df.to_csv('data/selected_books.csv', index=False)