# Generated by Django 4.2.1 on 2023-09-13 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')])),
                ('settings_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True)),
                ('plot_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True)),
                ('character_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True)),
                ('style_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True)),
                ('engagement_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
    ]
