# Generated by Django 4.2.1 on 2023-09-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='booknote',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='book.booknote'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('booknote', 'user')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='book',
        ),
    ]
