# Generated by Django 4.2.1 on 2023-09-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_rating_unique_together_rating_booknote_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
