# Generated by Django 4.2.1 on 2023-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknote',
            name='character_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True),
        ),
        migrations.AddField(
            model_name='booknote',
            name='engagement_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True),
        ),
        migrations.AddField(
            model_name='booknote',
            name='overall_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True),
        ),
        migrations.AddField(
            model_name='booknote',
            name='plot_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True),
        ),
        migrations.AddField(
            model_name='booknote',
            name='settings_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True),
        ),
        migrations.AddField(
            model_name='booknote',
            name='style_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Terrible'), (2, '2 - Not Good'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Loved it')], null=True),
        ),
    ]
