# Generated by Django 4.2.1 on 2023-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_booknote_character_rating_booknote_engagement_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_pages_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
