# Generated by Django 4.2.1 on 2023-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_userprofile_total_pages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
