# Generated by Django 4.2.1 on 2023-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_userprofile_favorite_genre_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_local',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
