# Generated by Django 4.2.1 on 2023-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_image_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
