# Generated by Django 4.2.1 on 2023-09-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_bookrequest_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='book',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='title',
            field=models.CharField(default='', max_length=350),
        ),
    ]
