# Generated by Django 4.2.1 on 2023-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_bookrequest_book_bookrequest_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='denial_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='denial_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
