# Generated by Django 4.2.1 on 2023-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='approval_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='approval_message_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
