# Generated by Django 4.2.1 on 2023-09-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_book_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.userprofile')),
            ],
        ),
    ]
