# Generated by Django 4.2.1 on 2023-09-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_usergenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.userprofile')),
            ],
        ),
    ]
